// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEKZUcjaqBGt35tB6cEMTjua81dget9o',
    appId: '1:950046010068:web:96655fa70aa90a8772a941',
    messagingSenderId: '950046010068',
    projectId: 'cater4lessrestaurant-c9bfa',
    authDomain: 'cater4lessrestaurant-c9bfa.firebaseapp.com',
    storageBucket: 'cater4lessrestaurant-c9bfa.firebasestorage.app',
    measurementId: 'G-DW26ZGR65H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAVIHh2_lStFRroeZieiBXaH48SQShm4c',
    appId: '1:950046010068:android:24de05e28b345e4172a941',
    messagingSenderId: '950046010068',
    projectId: 'cater4lessrestaurant-c9bfa',
    storageBucket: 'cater4lessrestaurant-c9bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SgyJ3IQLwVUtCXmRQ2uLyrN55SaWA3U',
    appId: '1:950046010068:ios:234cf2bca0931e3672a941',
    messagingSenderId: '950046010068',
    projectId: 'cater4lessrestaurant-c9bfa',
    storageBucket: 'cater4lessrestaurant-c9bfa.firebasestorage.app',
    iosBundleId: 'com.sixamtech.stackFoodRestaurant',
  );
}
