// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCU5TmqqAL4Nkl_9TxEMRUeCvCs0_TZ-ec",
      authDomain: "cater4lessdelivery.firebaseapp.com",
      projectId: "cater4lessdelivery",
      storageBucket: "cater4lessdelivery.firebasestorage.app",
      messagingSenderId: "553404915448",
      appId: "1:553404915448:web:a69c90e3a1dbd3124ea50d",
      measurementId: "G-J5HMN3RPR8"
    // apiKey: 'AIzaSyCU5TmqqAL4Nkl_9TxEMRUeCvCs0_TZ-ec',
    // appId: '1:553404915448:web:a69c90e3a1dbd3124ea50d',
    // messagingSenderId: '553404915448',
    // projectId: 'cater4lessdelivery',
    // authDomain: 'cater4lessdelivery.firebaseapp.com',
    // storageBucket: 'cater4lessdelivery.firebasestorage.app',
    // measurementId: 'G-J5HMN3RPR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArTy63ha7co3tl6uAxkx8jENcoBfhFgFg',
    appId: '1:553404915448:android:ed7ad37bf2b48a784ea50d',
    messagingSenderId: '553404915448',
    projectId: 'cater4lessdelivery',
    storageBucket: 'cater4lessdelivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxIzlFO_RK5A8Ut2ZPNcFad9zaEr1i2Y',
    appId: '1:553404915448:ios:77f7b2c400b787464ea50d',
    messagingSenderId: '553404915448',
    projectId: 'cater4lessdelivery',
    storageBucket: 'cater4lessdelivery.firebasestorage.app',
    iosBundleId: 'com.u6amtech.flutterRestaurant',
  );
}
